### ISSUE TITLE
Unnecessary code in code playground.

### ISSUE THREAD

**Issue by punitkr03** [mogulcoder26/OiDE-compiler#9]
There is unwanted code in code playground which prints this statement.
<img width="931" alt="b" src="https://github.com/mogulcoder26/OiDE-compiler/assets/50498807/f5bd96bc-6f94-46fd-8871-a9306c69dfde">
The return statement appears at top left corner.

**Comment by mogulcoder26** [comment]
Thank you for reporting this issue 
Closed as fixed
